# Site settings
title: Designer Portfolio
email: infotask@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance web designer and developer, specializing in Jekyll, HTML, CSS and Javascript.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: pamelavanbeekum
github_username:  infotask
google_username: infotask

permalink: /:categories/:title

# Build settings
markdown: kramdown
